name: Build Android APK (Capacitor)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build web (Vite)
        run: npm run build

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Capacitor CLI
        run: npm i -g @capacitor/cli

      - name: Add Android platform (idempotent)
        run: npx cap add android || echo "android already added"

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build Debug APK
        working-directory: ./android
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DinamitaBuilder-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
